--------------------------------------------------------------------------------Caso 1


SELECT NRO_PROPIEDAD "PROPIEDAD",
       UPPER(DIRECCION_PROPIEDAD) "DIRECCION",
       TO_CHAR(VALOR_ARRIENDO, '$999G999G999') "ARRIENDO",
       TO_CHAR(VALOR_GASTO_COMUN, '$999G999G999') "GGCC_ACTUAL",
       LPAD(TO_CHAR(ROUND((VALOR_GASTO_COMUN * 1.10)), '$999G999G999'), 15) "GGCC_AJUSTADO",
       (CASE
            WHEN ID_COMUNA = 82 THEN 'Propiedad ubicada en comuna 82'
            WHEN ID_COMUNA = 84 THEN 'Propiedad ubicada en comuna 84'
            WHEN ID_COMUNA = 87 THEN 'Propiedad ubicada en comuna 87'
            ELSE 'No aplica'
        END) AS "UBICACION"
FROM PROPIEDAD
WHERE VALOR_ARRIENDO < &VALOR_MAXIMO AND NRO_DORMITORIOS IS NOT NULL AND ID_COMUNA IN (82,84,87)
ORDER BY VALOR_GASTO_COMUN ASC NULLS LAST, "ARRIENDO" DESC;


--------------------------------------------------------------------------------Caso 2

SELECT NRO_PROPIEDAD "Propiedad",
       NUMRUT_CLI "Código Arrendatario",
       LOWER(TO_CHAR(FECINI_ARRIENDO, 'DD.mon.YYYY')) "Fecha Inicio Arriendo",
       NVL(LOWER(TO_CHAR(FECTER_ARRIENDO)), 'PROPIEDAD ACTUALMENTE ARRENDADA') "Fecha Término Arriendo",
       LPAD(TO_CHAR(TRUNC(NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO), '999G999' ), 15) "Días Arriendo",
       ROUND((NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO) / 365) "Años Arriendo",
       (CASE
            WHEN ROUND((NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO) / 365) >= 10 THEN 'COMPROMISO DE VENTA'
            WHEN ROUND((NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO) / 365) BETWEEN 5 AND 9 THEN 'CLIENTE ANTIGUO'
            ELSE 'CLIENTE NUEVO'
        END) AS "Clasificación Estado"
FROM ARRIENDO_PROPIEDAD
WHERE (NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO) >= &PERIODO_X
ORDER BY TRUNC(NVL(FECTER_ARRIENDO, SYSDATE) - FECINI_ARRIENDO) DESC;

--------------------------------------------------------------------------------Caso 3

SELECT ID_TIPO_PROPIEDAD "TIPO PROPIEDAD",
       (CASE
            WHEN ID_TIPO_PROPIEDAD = 'A' THEN 'Casa'
            WHEN ID_TIPO_PROPIEDAD = 'B' THEN 'Departamento'
            WHEN ID_TIPO_PROPIEDAD = 'C' THEN 'Local'
            WHEN ID_TIPO_PROPIEDAD = 'D' THEN 'Parcela sin casa'
            WHEN ID_TIPO_PROPIEDAD = 'E' THEN 'Parcela con casa'
            ELSE 'No aplica'
        END) AS "DESCRIPCION",
        LPAD(TO_CHAR(ROUND(AVG(VALOR_GASTO_COMUN)), '$999G999'), 25) "PROMEDIO GASTO COMUN",
        COUNT(NRO_PROPIEDAD) "CANTIDAD PROPIEDADES",
        LPAD(TO_CHAR(ROUND(AVG(NVL(VALOR_ARRIENDO, 0))), '$999G999G999'), 25) "PROMEDIO VALOR ARRIENDO"
FROM PROPIEDAD
GROUP BY ID_TIPO_PROPIEDAD
HAVING ROUND(AVG(VALOR_ARRIENDO)) >= &ARRIENDO_MINIMO
ORDER BY ID_TIPO_PROPIEDAD ASC, (ROUND(AVG(VALOR_ARRIENDO))) DESC;

